### ISSUE TITLE
September 25th Action failed

### ISSUE THREAD

**Issue by 1171000408** [Dr-TSNG/HIT-clock#19]
In the morning of September 25th, this script has failed. The reason is that url https://xg.hit.edu.cn/zhxy-xgzs/xg_mobile/xsMrsbNew is not exist anymore (return 404), new url is https://xg.hit.edu.cn/zhxy-xgzs/xg_mobile/xsMrsbNew/index

**Comment by Dr-TSNG** [comment]
Updated
