### ISSUE TITLE
上报失败了

### ISSUE THREAD

**Issue by MayeZhang** [Dr-TSNG/HIT-clock#3]
![image](https://user-images.githubusercontent.com/42532687/121973771-9274d300-cdb0-11eb-94e4-fb7b98c00cf1.png)

您好，请问一下上报失败了是什么情况啊。就今天失败了，前几天都好好的啊

**Comment by Dr-TSNG** [comment]
很正常，重新运行一次就行了，可能是网络不稳定（指工大土豆服务器）
