### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by RyanLoil** [Dr-TSNG/HIT-clock#34]
Got information that the school department is planning to punish the automatic-report project.

**Comment by Dr-TSNG** [comment]
Really? That's a little haren

**Comment by RyanLoil** [comment]
Yeah, very 哈人. I think they are trying to use host which may be the same when GitHub runs the test script to identify who is using the automatic report robot. It has great chance that they already have noticed this project exisitance.
Prepare for this, and remove all your personal information from public profile, I don't know when they'll coming for this project or if they are still pay attention on it.

**Comment by RyanLoil** [comment]
Yeah, very 哈人. I think they are trying to use host which may be the same when GitHub runs the test script to identify who is using the automatic report robot. It has great chance that they already have noticed this project exisitance.
Prepare for this, and remove all your personal information from public profile, I don't know when they'll coming for this project or if they are still pay attention on it.

**Comment by Dr-TSNG** [comment]
You are right, I should suspend this project for sometime until the epidemic is not so serious. Thanks for your information.
