### ISSUE TITLE
Somehow today my action-job failed

### ISSUE THREAD

**Issue by RyanLoil** [Dr-TSNG/HIT-clock#42]
Today, my action-job failed and the exception is cannot find element of class name "submit", and all checkbox is missing 5 times. But when I tested it in my own pc, it worked fine.
There is a chance that GitHub's ip may be on a black list of HIT-XG, but I can't confirm that as I reran my job after the test, it worked normally.
Have any ideas?

**Comment by Dr-TSNG** [comment]
Maybe it's just an accident 🤔?

**Comment by RyanLoil** [comment]
Yeah, maybe. It never happened again in the past 10 days after all.

**Comment by RyanLoil** [comment]
<img width="518" alt="image" src="https://user-images.githubusercontent.com/50242494/184670688-a23bbd91-7ec3-4238-a25b-52c933200b36.png">

**Comment by 0x401000Nu1l** [comment]
@RyanLoil 可能是那天已经申请过出校，然后界面变化之后再次运行脚本就申请不了了

**Comment by RyanLoil** [comment]
Showed up again twice without applying out-of-school 

> Reference in

**Comment by Dr-TSNG** [comment]
Because of 0x16 Big, CERNET was blocked by the GFW, so GitHub server cannot connect to the server, it may last for 3 day~1 week.
