### ISSUE TITLE
是不是现在上报不上去了？

### ISSUE THREAD

**Issue by yhao-z** [Dr-TSNG/HIT-clock#43]
是我自己出问题了吗？

**Comment by Jason-Deng25** [comment]
我这儿也不行了，发一下报错的显示

Run python 每日上报.py
初始化浏览器
正在上报
No such checkbox: txfscheckbox
截图失败
Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot take screenshot with 0 width."}
  (Session info: headless chrome=[10](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:11)4.0.5[11](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:12)2.101)
Stacktrace:
#0 0x55b5f4c0f403 <unknown>
#1 0x55b5f4a15778 <unknown>
#2 0x55b5f4a02fbe <unknown>
#3 0x55b5f4a018b5 <unknown>
#4 0x55b5f4a01c1c <unknown>
#5 0x55b5f4a1d1fe <unknown>
#6 0x55b5f4a4a60c <unknown>
#7 0x55b5f4a6aa02 <unknown>
#8 0x55b5f4a41703 <unknown>
#9 0x55b5f4a6ab0e <unknown>
#10 0x55b5f4a7dc74 <unknown>
#11 0x55b5f4a6a8f3 <unknown>
#[12](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:13) 0x55b5f4a400d8 <unknown>
#[13](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:14) 0x55b5f4a41205 <unknown>
#[14](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:15) 0x55b5f4c56e3d <unknown>
#[15](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:16) 0x55b5f4c59db6 <unknown>
#[16](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:17) 0x55b5f4c4013e <unknown>
#[17](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:18) 0x55b5f4c5a9b5 <unknown>
#[18](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:19) 0x55b5f4c34970 <unknown>
#[19](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:20) 0x55b5f4c77228 <unknown>
#[20](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:21) 0x55b5f4c773bf <unknown>
#[21](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:22) 0x55b5f4c91abe <unknown>
#[22](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:23) 0x7f868b01[26](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:27)09 <unknown>

截图失败
Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot take screenshot with 0 width."}
  (Session info: headless chrome=104.0.5112.101)
Stacktrace:
#0 0x55b5f4c0f403 <unknown>
#1 0x55b5f4a15778 <unknown>
#2 0x55b5f4a02fbe <unknown>
#3 0x55b5f4a018b5 <unknown>
#4 0x55b5f4a01c1c <unknown>
#5 0x55b5f4a1d1fe <unknown>
#6 0x55b5f4a4a60c <unknown>
#7 0x55b5f4a6aa02 <unknown>
#8 0x55b5f4a41703 <unknown>
#9 0x55b5f4a6ab0e <unknown>
#10 0x55b5f4a7dc74 <unknown>
#11 0x55b5f4a6a8f3 <unknown>
#12 0x55b5f4a400d8 <unknown>
#13 0x55b5f4a41205 <unknown>
#14 0x55b5f4c56e3d <unknown>
#15 0x55b5f4c59db6 <unknown>
#16 0x55b5f4c4013e <unknown>
#17 0x55b5f4c5a9b5 <unknown>
#18 0x55b5f4c34970 <unknown>
#19 0x55b5f4c772[28](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:29) <unknown>
#20 0x55b5f4c773bf <unknown>
#21 0x55b5f4c91abe <unknown>
#22 0x7f868b012609 <unknown>

截图失败
Message: unknown error: unhandled inspector error: {"code":-[32](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:33)000,"message":"Cannot take screenshot with 0 width."}
  (Session info: headless chrome=104.0.5112.101)
Stacktrace:
#0 0x55b5f4c0f403 <unknown>
#1 0x55b5f4a15778 <unknown>
#2 0x55b5f4a02fbe <unknown>
#3 0x55b5f4a018b5 <unknown>
#4 0x55b5f4a01c1c <unknown>
#5 0x55b5f4a1d1fe <unknown>
#6 0x55b5f4a4a60c <unknown>
#7 0x55b5f4a6aa02 <unknown>
#8 0x55b5f4a41703 <unknown>
#9 0x55b5f4a6ab0e <unknown>
#10 0x55b5f4a7dc74 <unknown>
#11 0x55b5f4a6a8f3 <unknown>
#12 0x55b5f4a400d8 <unknown>
#13 0x55b5f4a41205 <unknown>
#14 0x55b5f4c56e3d <unknown>
#15 0x55b5f4c59db6 <unknown>
#16 0x55b5f4c4013e <unknown>
#17 0x55b5f4c5a9b5 <unknown>
#18 0x55b5f4c[34](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:35)970 <unknown>
#19 0x55b5f4c77228 <unknown>
#20 0x55b5f4c773bf <unknown>
#21 0x55b5f4c91abe <unknown>
#22 0x7f868b012609 <unknown>

截图失败
Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot take screenshot with 0 width."}
  (Session info: headless chrome=104.0.5112.101)
Stacktrace:
#0 0x55b5f4c0f[40](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:41)3 <unknown>
#1 0x55b5f4a15778 <unknown>
#2 0x55b5f4a02fbe <unknown>
#3 0x55b5f4a018b5 <unknown>
#4 0x55b5f4a01c1c <unknown>
#5 0x55b5f4a1d1fe <unknown>
#6 0x55b5f4a4a60c <unknown>
#7 0x55b5f4a6aa02 <unknown>
#8 0x55b5f4a[41](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:42)703 <unknown>
#9 0x55b5f4a6ab0e <unknown>
#10 0x55b5f4a7dc74 <unknown>
#11 0x55b5f4a6a8f3 <unknown>
#12 0x55b5f4a400d8 <unknown>
#13 0x55b5f4a41205 <unknown>
#14 0x55b5f4c56e3d <unknown>
#15 0x55b5f4c59db6 <unknown>
#16 0x55b5f4c4013e <unknown>
#17 0x55b5f4c5a9b5 <unknown>
#18 0x55b5f4c3[49](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:50)70 <unknown>
#19 0x55b5f4c77228 <unknown>
#20 0x55b5f4c773bf <unknown>
#21 0x55b5f4c91abe <unknown>
#22 0x7f868b012609 <unknown>

截图失败
Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot take screenshot with 0 width."}
  (Session info: headless chrome=104.0.[51](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:52)12.101)
Stacktrace:
#0 0x[55](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:56)b5f4c0f403 <unknown>
#1 0x55b5f4a15778 <unknown>
#2 0x55b5f4a02fbe <unknown>
#3 0x55b5f4a018b5 <unknown>
#4 0x55b5f4a01c1c <unknown>
#5 0x55b5f4a1d1fe <unknown>
#6 0x55b5f4a4a60c <unknown>
#7 0x55b5f4a6aa02 <unknown>
#8 0x55b5f4a41703 <unknown>
#9 0x55b5f4a6ab0e <unknown>
#10 0x55b5f4a7dc74 <unknown>
#11 0x55b5f4a6a8f3 <unknown>
#12 0x55b5f4a400d8 <unknown>
#13 0x55b5f4a41205 <unknown>
#14 0x55b5f4c[56](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:57)e3d <unknown>
#15 0x55b5f4c59db6 <unknown>
#16 0x55b5f4c4013e <unknown>
#17 0x55b5f4c5a9b5 <unknown>
#18 0x55b5f4c34970 <unknown>
#19 0x55b5f4c77228 <unknown>
#20 0x55b5f4c773bf <unknown>
#21 0x55b5f4c91abe <unknown>
#22 0x7f868b012609 <unknown>

截图失败
Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot take screenshot with 0 width."}
  (Session info: headless chrome=104.0.5112.101)
Stacktrace:
#0 0x55b5f4c0f403 <unknown>
#1 0x55b5f4a1[57](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:58)78 <unknown>
#2 0x55b5f4a02fbe <unknown>
#3 0x55b5f4a018b5 <unknown>
#4 0x55b5f4a01c1c <unknown>
#5 0x55b5f4a1d1fe <unknown>
#6 0x55b5f4a4a60c <unknown>
#7 0x55b5f4a6aa02 <unknown>
#8 0x55b5f4a41703 <unknown>
#9 0x55b5f4a6ab0e <unknown>
#10 0x55b5f4a7dc74 <unknown>
#11 0x55b5f4a6a8f3 <unknown>
#12 0x55b5f4a400d8 <unknown>
#13 0x55b5f4a41205 <unknown>
#14 0x55b5f4c56e3d <unknown>
#15 0x55b5f4c[59](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:60)db6 <unknown>
#16 0x55b5f4c4013e <unknown>
#17 0x55b5f4c5a9b5 <unknown>
#18 0x55b5f4c34970 <unknown>
#19 0x55b5f4c77228 <unknown>
#20 0x55b5f4c773bf <unknown>
#21 0x55b5f4c91abe <unknown>
#22 0x7f868b012[60](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:61)9 <unknown>

截图失败
Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot take screenshot with 0 width."}
  (Session info: headless chrome=104.0.5112.101)
Stacktrace:
#0 0x55b5f4c0f403 <unknown>
#1 0x55b5f4a15778 <unknown>
#2 0x55b5f4a02fbe <unknown>
#3 0x55b5f4a018b5 <unknown>
#4 0x55b5f4a01c1c <unknown>
#5 0x55b5f4a1d1fe <unknown>
#6 0x55b5f4a4a60c <unknown>
#7 0x55b5f4a6aa02 <unknown>
#8 0x55b5f4a41703 <unknown>
#9 0x55b5f4a6ab0e <unknown>
#10 0x55b5f4a7dc74 <unknown>
#11 0x55b5f4a6a8f3 <unknown>
#12 0x55b5f4a400d8 <unknown>
#13 0x55b5f4a41205 <unknown>
#14 0x55b5f4c56e3d <unknown>
#15 0x55b5f4c59db6 <unknown>
#16 0x55b5f4c4013e <unknown>
#17 0x55b5f4c5a9b5 <unknown>
#18 0x55b5f4c34970 <unknown>
#19 0x55b5f4c77228 <unknown>
#20 0x55b5f4c773bf <unknown>
#21 0x55b5f4c91abe <unknown>
#22 0x7f8[68](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:69)b0[126](https://github.com/Jason-Deng25/HIT-clock/runs/8061191087?check_suite_focus=true#step:6:127)09 <unknown>

上报完成

**Comment by RyanLoil** [comment]
看到了，这个不是因为上报失败，而是因为原来有时候弹出验证码，为此我们增加了验证码识别，现在来看他们把验证码取消了，所以会报这种错误。我这几天并没有接受到未填报的通知，所以这个错误应该不是问题。

**Comment by RyanLoil** [comment]
如果有问题，请继续告知我们

**Comment by yhao-z** [comment]
好的好的，非常非常感谢！
