### ISSUE TITLE
10月14号之后就一直上报失败了，是学工系统又更新了吗

### ISSUE THREAD

**Issue by N0MOREE** [Dr-TSNG/HIT-clock#48]

**Comment by Dr-TSNG** [comment]
Because of 0x16 Big, CERNET was blocked by the GFW, so GitHub server cannot connect to the server, it may last for 3 day~1 week.

**Comment by Dr-TSNG** [comment]
Fixed in https://github.com/Dr-TSNG/HIT-clock/commit/3089ff45b17c602d5a842f73cc118aa7acbb05e6
